### ISSUE TITLE
trigger navigation after adding new image

### ISSUE THREAD

**Issue by pieterdegraeuwe** [Ks89/angular-modal-gallery#127]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X? ] Feature request
[ ] Documentation issue or request
[ X] Support request
</code></pre>

## Current behavior

I'm using the ks-modal-gallery with a buttonsConfig which contains a customButton.
Once clicked I do some logic and add a new image to the images array (it is added at the end of the array) .
All works fine. I can see the extra 'dot' and I can navigate to it.... 

## Expected behavior
...but, it would be nice that, when the image is added, it automatically shows the image in preview, so I'm looking for a way to navigate to a specific image.
Is that possible?

## Environment (the most important section to fill very carefully)
All works fine, I'm using angular-modal-gallery version 5.1.0

Browser:
- [ X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by Ks89** [comment]
Interesting question.
I'll think something, because at the moment I don't have a good idea to implement it.

I'll update this issue in some days with an update. Please be patient.

**Comment by Ks89** [comment]
I made some experiments and It's not so simple to implement. However, I'll try to add it in one of the next 5.x.x releases.

I'll update this issue when I'll have a beta of this feature, because It will require some beta testing to create a stable version.

**Comment by Ks89** [comment]
I decided to increase the priority because requested also by another user.
I'll publish alphas and betas for this feature because it's really challenging.
PS: I hope to release this in April

**Comment by Ks89** [comment]
I have an experimental implementation. I'll release it as alpha/beta at the beginning of April.

Before, I have to release 5.4.0 (in beta right now) and another small version 5.5.0 already scheduled.

So this feature will be released as 5.6.0 in April.

**Comment by Ks89** [comment]
update: I'll release a beta version of gallery.service to implement this feature in a couple of days.
I'll also add an example with this feature already implemented.

**Comment by Ks89** [comment]
@pieterdegraeuwe 

Finally after many commits it's time for the first beta release of gallery service.
https://github.com/Ks89/angular-modal-gallery/releases

To try the beta: `npm i --save angular-modal-gallery@beta`

I'm still working on the new doc, so if you want to try please check to the official examples in this repo (folder /examples).

In particular I suggest to look for example `B23 - (id=37)` where you can see the feature you requested already implemented. 

As you can see it seems slow, but this happens because in my example I have more than 40 instances of modal gallery in a single page. This won't happen in real scenarios. Feel free to try in your application and add a comment here with your feedback.

**Comment by Ks89** [comment]
5.6.0 with gallery.service officially released.

Feel free to re-open if you have problems.
