### ISSUE TITLE
Set image-name for download

### ISSUE THREAD

**Issue by SebastianFreund** [Ks89/angular-modal-gallery#146]
Hey,
is it possible to specify the name to use when downloading the image? I do base64 strings as src for the images instead of urls. The name of the downloaded files is then very cryptic (it seems to be the end of the src string) and usually without the correct file extension.

**Comment by Ks89** [comment]
Not at the moment, I'm using the name of the image from its path to create the filename.
However there are some limitation about image download in modern browsers, so I'm still thinking and searching a better approach. Right now, I don't want to add other features about this topic, because probably I'll rewrite it from scratch. 

If you have a good idea to download images automatically also from different origins (for instance from another server) bypassing browsers security features feel free to share it.

**Comment by SebastianFreund** [comment]
Maybe you can add a option to use the 'title' or 'alt' as name for the downloaded image?

**Comment by Ks89** [comment]
Yes this is an option, but I scheduled to investigate about better alternatives for image download in 7.0.0.
I'll update you when I'll find something new.

**Comment by Ks89** [comment]
I decided to add a new propertie into Image class to choose the file name. I'll release it as 6.1.0.

When I'll find a new way to download images, probably I'll change it, but for now this should be ok.

**Comment by Ks89** [comment]
6.1.0 release with this feature

**Comment by SebastianFreund** [comment]
It works fine! Thanks!
