### ISSUE TITLE
Different image URLs for the Thumbnails and image preview

### ISSUE THREAD

**Issue by asarapas** [Ks89/angular-modal-gallery#155]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

Same image is used for the Thumbnail and Image preview

## Expected behavior

Thumbnail Image URL could be used for the Thumbnails and actual / larger image url could be used for displaying actual image

## What is the motivation / use case for changing the behavior?

Minimise data transferred and increase performance

**Comment by Ks89** [comment]
Hi, I'm sorry but I'm not understand. Could you explain again with more details?

 What it means 'Image preview'? Side previews or previews at the bottom of the modal view?

> Thumbnail Image URL could be used for the Thumbnails and actual / larger image url could be used for displaying actual image

This is already implemented. You can define 2 urls, one inside the modal object and another one into plain object.
Image interface is here: https://ks89.github.io/angular-modal-gallery-2018-v6.github.io/features/modal-gallery
And here you can find the plain configuration: https://ks89.github.io/angular-modal-gallery-2018-v6.github.io/features/plain-gallery

When you define something in plain object, it will always win, otherwise modal url will be used.

**Comment by asarapas** [comment]
Sorry, my bad. Did not spend enough time on the gallery to understand meaning of the plain object. Gallery certainly works the way you have described and that's exactly what I was looking for. Thank you for the superb product, outstanding support.
