### ISSUE TITLE
Lazy load images in modal

### ISSUE THREAD

**Issue by timmyrosen** [Ks89/angular-modal-gallery#181]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

I have a rather large array of images (like 50+), and right now when I open the gallery modal all of the images are loaded simultaneously.

## Expected behavior

Lazy loading of images, preferably with an option to set number of images before and after current image to preload.

## What is the motivation / use case for changing the behavior?

Lazy loading of images would increase performance in cases such as mine when dealing with large arrays of images, and decrease bandwidth, which is especially important for mobile users

## Environment (the most important section to fill very carefully)

<pre><code>
- @ks89/angular-modal-gallery version: 7.2.1
- Node version: 10.0.0  
- npm version: 6.4.1  
- Operating System and version: MacOS 10.14.3
- Angular version: 7.2.3
- angular-cli version (or SystemJS/Webpack): 7.3.0
- I'm using Server Side Rendering with angular-universal: NO
- I'm compiling with mode: PROD with AOT

**Comment by Ks89** [comment]
Hi.

This is a very common question and probably I should improve the doc with a dedicated section, because many users seem confused. 

Basically, this feature is already implemented in this way:
To use lazy loading you have to add both modal and plain image. Use a smaller plain image and the full size modal image. In this way the library will load plain images (you con also limit the number) and when you click on a plain image, the library will load the modal gallery with a full size image.

**Comment by timmyrosen** [comment]
I searched the issues here but couldn't find any related thread.

As of now I use my own custom thumbnail component and when clicked I call openGallery for the modal. The reason for this was a lack of customization options in the plain gallery. However in recent update I notice an improvement in customizing the plain gallery component and I might be able to configure and use it to my liking.

Thanks!
