### ISSUE TITLE
how to add loading when element is deleted from galery

### ISSUE THREAD

**Issue by simona-luca** [Ks89/angular-modal-gallery#185]
## I'm submitting a...
[ x ] Feature request
[ x ] Support request

## Current behavior

When deleting an image there is no feedback for the user. So it takes few secs until the image dissapears from galery and few more until dissapears from preview-container. 

## Expected behavior

A loading would be nice to have when deleting an element from galery. 
Can you please help me to add it ?

Thx for consideration!

## Environment (the most important section to fill very carefully)

<pre><code>
- @ks89/angular-modal-gallery version: ^7.2.1"

Browser:
- [ x ] Chrome (desktop) version XX

**Comment by Ks89** [comment]
Hi @simona-luca,
I didn't add the spinner because it shouldn't be so slow.
Did you try to monitor performances with Chrome dev tool to see where is a problem (javascript or rendering)?

Please could your environment? For instance:
- Operating system
- npm version 
- node version
- if you are using server side rendering or not
- if you are building as production with AOT and all best practices in angular-cli
- angular version
- which is the size (in Bytes and also as height x width in pixels) of the images and how many images did you add to the gallery?
- chrome version
- and all other possible info

**Comment by Ks89** [comment]
Closed because without answer. Feel free to comment if you still have this issue.
