### ISSUE TITLE
add new feature : zoom in mouse scrollwheel current image

### ISSUE THREAD

**Issue by oveshparasara** [Ks89/angular-modal-gallery#190]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Minimal reproduction of the problem with instructions

My official live example on StackBlitz (based on https://stackblitz.com/edit/angular-modal-gallery-v7) is: 

## Environment (the most important section to fill very carefully)

<pre><code>
- @ks89/angular-modal-gallery version: X.X.X
- Node version: X.X.X  
- npm version: X.X.X  
- Operating System and version:  
- Angular version: X.Y.Z 
- angular-cli version (or SystemJS/Webpack): X.Y.Z 
- I'm using Server Side Rendering with angular-universal: YES/NO
- I'm compiling with mode: DEBUG / PROD / PROD with AOT

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

**Comment by Ks89** [comment]
Please explain your request in a better way, because I cannot understand.

**Comment by oveshparasara** [comment]
currentImageConfig adde configuration for zoom image

**Comment by Ks89** [comment]
Hi.
If you want so zoom the image with your mouse, it isn't something that I want to add, because platform specific (only desktops).

This library must work in the same way also on mobile, where you don't have a mouse. 

So the only way is to add buttons to zoom the image, but I won't add this quickly. 
For sure not in the next major release.

At the moment, I close the issue. 
If you want to add other information or idea feel free to update this issue.
