### ISSUE TITLE
Modal mode very slow with big galleries

### ISSUE THREAD

**Issue by giTonyx** [Ks89/angular-modal-gallery#202]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
</code></pre>

## Current behavior

When I load a (plain) gallery with over 2000 images, loading the thumbnail is reasonably fast, but then opening the images is very slow (and also when you have loaded an image and press left or right to change image it's very slow as well). It takes about 3-4 seconds for a 130KB image. 

## Expected behavior

Moving between images should be faster, or at least proportional to the image size.

## Minimal reproduction of the problem with instructions
Just add 2000 images to any gallery.

## What is the motivation / use case for changing the behavior?

Would like to have a very big gallery.

## Environment (the most important section to fill very carefully)

<pre><code>
- @ks89/angular-modal-gallery version: X.X.X
- Node version: X.X.X  
- npm version: X.X.X  
- Operating System and version:  
- Angular version: X.Y.Z 
- angular-cli version (or SystemJS/Webpack): X.Y.Z 
- I'm using Server Side Rendering with angular-universal: YES/NO
- I'm compiling with mode: DEBUG / PROD / PROD with AOT

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

**Comment by giTonyx** [comment]
I've created a minimal example: https://stackblitz.com/edit/angular-czxzxr
And maybe it's not related to the size (or maybe there are two different issues).

In this example I only have to images.
If I:
1) reload the page
2) click on first image
3) click on the right arrow

It loads forever.

Note that, instead, if I:
1) reload the page
2) click on first image
3) close image
4) click on second image
Now the arrows work correctly.

**Comment by Ks89** [comment]
A browser caches images and won't emit the 'load' event again for the same url.

This question has been asked other times and the only solution that I found is to append a progressive number as query parameter.
Based on your example I modified ngOnInit in this way:

```
  ngOnInit(): void {
    let new_images = [];
    let i=0;
    while (new_images.length < 2) {

      new_images.push(new Image(new_images.length, {
        img: 'https://raw.githubusercontent.com/Ks89/angular-modal-gallery/master/examples/systemjs/assets/images/gallery/img1.jpg?' + i
      }));

      i++;
    
    }
    this.images = new_images;
  }
```

**Comment by Ks89** [comment]
About the performance it's not so easy to test, because I need an array of 2000 remote different images.

I never tested a gallery so big. Which is the purpose of adding 2000 images to the same gallery? 
How can you navigate between 2000 images? Honestly, it seems a little bit crazy from the UX point of view.

**Comment by giTonyx** [comment]
Damn, sorry. I was wondering why that small test with only 2 images was not working at all. Sorry, was a typo to have the same ID, I knew they had to be different. Sorry again.

I've updated my previous demo to include a big gallery: https://stackblitz.com/edit/angular-czxzxr

The use case is to create a slideshow from the images of a facebook profile. 
Maybe indeed such a big gallery is unreasonable.

**Comment by Ks89** [comment]
Oh, I'm sorry, I totally missed your response.

Open the page with Chrome, but don't click on any image. Then, show Chrome Dev Tools (Network tab). As you can see, the browser is blocked getting all images from the server.
If you want to use so many images, you should show only some images with a full custom plain gallery with a sort of +1000 as last image. I already implemented some examples on stackblitz (plain gallery tab). In this way you can show only some images in a faster way without blocking the browser.
If you prefer, you can also create a custom implementation to load images scrolling the browser (or with a button "load more" in the end, but this is up to you.

Then it could be interesting to see if the library is still slow. Because your example is not a reasonable scenario. No one want to load 2000 images opening a page, without to have a sort of paging/load more or something else.

However, thanks for reporting this with your example, because it could be useful to test a situation with many images to see how the library responds. If you want to help me to update your example with a custom plain gallery, then we could check if the behaviour is the same or if it's faster.

**Comment by giTonyx** [comment]
Thanks for the answer. It makes sense, I guess.
And thanks for the great support you are providing answering all kind of questions!

**Comment by Ks89** [comment]
Issue closed. Feel free to open it again if required.
