### ISSUE TITLE
Remove hammerjs dependency? 

### ISSUE THREAD

**Issue by HarelM** [Ks89/angular-modal-gallery#218]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
Documentation says that I need to install hammerjs

## Expected behavior
Recent versions of material removed the dependency of hammerjs and also it seems that the current gallery I'm using managed to do it too: `angular-gallery` So I was wondering if this is also the direction here.

## What is the motivation / use case for changing the behavior?
Reduce dependencies

## Other comments
I'm not using this library but I want to migrate out of a library that has stopped being maintained.
I'm considering my options.
What I basically need is the ability to open a set of images and allow the user to change them (enlarge them).
The behavior can be seen here:
https://israelhiking.osm.org.il/poi/OSM/node_2209019954?language=he
By clicking the image the gallery opens and shows the images.
What is currently missing:
1. The ability to pitch-zoom the image to enlarge it even further
2. On mobile devices the image is not taking the entire space which creates a small image - which is counter prodcutive

As a side note, the documentation page is returning a 404 right now.

I would love to help out and test/contribute/whatever you need. This is a nice feature which I would like to keep up-to-date and I'm really impressed by the rate of your releases.

**Comment by Ks89** [comment]
Hi thank you for your interest in this project.
Yes, I know that it's possible to remove it, however I didn't try to do it.

I'm trying to release v8.0.0 as stable version, but I still need to write a test and the new doc website.
This is the highest priority right now. So I won't add any new feature until version 8.0.0 will be ready for the release as stable version. I don't have enough spare time to predict any release date.

Next, I can try to schedule requests and so on.

`1. The ability to pitch-zoom the image to enlarge it even further`

I don't remember If I made experiments about this, however I don't consider this something with high priority.

`2. On mobile devices the image is not taking the entire space which creates a small image - which is counter prodcutive`

This is challenging because it may require many changes to layout and CSS. So I don't expect to implement it, in particular because some users are still using the library on IE11. Probably, the only way to do it smoothly is to remove IE11 compatibility and redesign modal view in a smarter way, without considering obsolete browsers. This is probably the right direction to clean up CSS/HTML and speed up development of UI changes.

Any contribution is welcome, however, as I sad, at the moment I want to complete v8.0.0 so If you want to help me to update doc website (here https://github.com/Ks89/angular-modal-gallery-2020-v8.github.io) or add the missing spec file of modal-gallery component (https://github.com/Ks89/angular-modal-gallery/blob/develop/projects/ks89/angular-modal-gallery/src/lib/components/modal-gallery/modal-gallery.component.ts), we can speed up development.

**Comment by Ks89** [comment]
About point 1, I fond this older issue https://github.com/Ks89/angular-modal-gallery/issues/158.
There was a problem with hammerjs and I also opened an issue directly in the hammerjs repo, but no one answered in about 2 years.

Hammer support is very bad. There are tons of older issues without answers.

**Comment by HarelM** [comment]
Thanks to the info.
Note there I think angular 11 dropped support for ie 11 so I think it's a no brainer...
Also other libraries version are marching the version of angular they support, you might want to consider this as well - I.e release version 8 but call it 11 to let developers know which version they should use with each angular version.
This way you can also say that you can use version 6 or whatever with ie but the latest version doesn't support it.
In any case I'll have a look in the code and see if I can help out...

**Comment by HarelM** [comment]
Thanks for the info, I ended up moving to photoswipe to achieve pintch-zoom and swipe left-right to change images on mobile.
Good luck with this library!!
