### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by kejtizuki** [Ks89/angular-modal-gallery#24]
Hey, I'm trying to use your modal gallery with webpack. I did everything exactly as in the section how to use it and I get the following error: _Uncaught SyntaxError: Unexpected token import_
Any idea what may be wrong?

**Comment by Ks89** [comment]
Did you see the official example inside demo/webpack folder (in the source code of this repository) ? I created it using the 
It is possible that I made a mistake while writing the Readme. The official demo was working, since I deployed it on github pages. 

Could you post these versions: angular-modal-gallery,  webpack, angular, node js and also which operating e system? And all other important infos, for example if you are using webpack2 treeshaking or with a vendor.ts.
Also,  could post here you webpack config or your repository? 

I want to help you to fix this problem, but I need more information.

**Comment by Ks89** [comment]
Damn! These is a problem with one or more dependencies in the official webpack's demo. I'm really sorry about that. In my previous post I said the everything was ok, but this is not the true. 

I pushed a fix to force all deps to a specific version. I'll fix this with a new major release (3.0.0), still inside the 'develop' branch, because under development.

I'll hope to release 3.0.0 before the end of this month. 🥇

**Comment by Ks89** [comment]
Hi @kejtizuki , do you have any updates?

**Comment by Ks89** [comment]
Closed by inactivity.

If you need more help, please re-open this issue.
