### ISSUE TITLE
 'ButtonsConfig' was not found in './modal-gallery.component'

### ISSUE THREAD

**Issue by Beelphegor** [Ks89/angular-modal-gallery#71]
Getting this warnings after updating the library to 3.1.1
I had to rollback to 3.0.1 to get rid of them, couldn't figure out what was the problem.

WARNING in ./~/angular-modal-gallery/src/components/upper-buttons.component.ts
59:50-63 "export 'ButtonsConfig' was not found in './modal-gallery.component'

WARNING in ./~/angular-modal-gallery/src/components/upper-buttons.component.ts
59:83-96 "export 'ButtonsConfig' was not found in './modal-gallery.component'

WARNING in ./~/angular-modal-gallery/src/directives/external-url-button.directive.ts
82:50-63 "export 'ButtonsConfig' was not found in '../components/modal-gallery.component'

WARNING in ./~/angular-modal-gallery/src/directives/external-url-button.directive.ts
82:83-96 "export 'ButtonsConfig' was not found in '../components/modal-gallery.component'

WARNING in ./~/angular-modal-gallery/src/directives/download-button.directive.ts
61:50-63 "export 'ButtonsConfig' was not found in '../components/modal-gallery.component'

WARNING in ./~/angular-modal-gallery/src/directives/download-button.directive.ts
61:83-96 "export 'ButtonsConfig' was not found in '../components/modal-gallery.component'

WARNING in ./~/angular-modal-gallery/src/directives/close-button.directive.ts
62:50-63 "export 'ButtonsConfig' was not found in '../components/modal-gallery.component'

WARNING in ./~/angular-modal-gallery/src/directives/close-button.directive.ts
62:83-96 "export 'ButtonsConfig' was not found in '../components/modal-gallery.component'

**Comment by Ks89** [comment]
Hi thank u for you interest. 
It's strange, because I'm using this version on 3 projects (one of them is the documentation and it's production ready) and also on 3 different CI environments... So I suppose that it's a problem related with npm. 

Are you using npm 5? If yes, did you try to update the version of this library in your package.json, after that to remove package-lock.json and the entire node_module folder? Finally run npm install to reinstall everything from scratch. 

Ps: which OS and angular versions?

**Comment by Ks89** [comment]
I checked and I confirm this issue. It's not a blocking issue, but I'll investigate.

**Comment by Ks89** [comment]
Ps it's happening only with angular-cli

**Comment by Ks89** [comment]
@Beelphegor it's an angular-cli issue. Check here: https://github.com/angular/angular-cli/issues/2034

I add the "WAITING" label to say that it's an issue that I can't fix at the moment, but I'm waiting for the official fix.

**Comment by dvh312** [comment]
Same here! Mac OS 10.12.6, Angular 4.

**Comment by Ks89** [comment]
@dvh312 If you want, I can try one of these workarounds (https://github.com/angular/angular-cli/issues/2034) releasing version 3.2.1.
When the final fix will be released by Google, I'll push version 3.2.2 with the final fix.
Is it ok for you?

**Comment by dvh312** [comment]
I'm fine with the warning. Take your time 👍

**Comment by bittusinghintruder** [comment]
I am also facing the same issue. When this can be get resolved.

**Comment by dvh312** [comment]
@bittusinghintruder Maybe @Ks89  will try the workaround in the next release and he will fix it soon in 3.2.2.

**Comment by Ks89** [comment]
I'm really happy that you are using this library and you are interested in its development. :)

Ok, I'll try a workaround and I'll push 3.2.1 this weekend (I need some time to test all demos, documentation and so on to be sure to release a working version, since I'm developing this library during my spare time).

PS: if you have feature request and so on, please open an issue XD.

**Comment by Ks89** [comment]
3.2.1 released

Could you try this version? https://github.com/Ks89/angular-modal-gallery/releases/tag/v3.2.1

**Comment by dvh312** [comment]
@Ks89 No more warnings!!! Thank you very much. +1

**Comment by Ks89** [comment]
@bittusinghintruder and @Beelphegor can you close this issue?
Thank u.

**Comment by bittusinghintruder** [comment]
Sorry for the late rely, will try today and let you know. Thanks.. :)

**Comment by bittusinghintruder** [comment]
Wow cool @Ks89. No more warnings!!!!!!  You may close this issue from my side. Thank you very much.
