### ISSUE TITLE
Support configurable buttons [Feature request]

### ISSUE THREAD

**Issue by Enngage** [Ks89/angular-modal-gallery#92]
## What is the motivation / use case for changing the behavior?

The `buttonsConfig ` could be made configurable so that you could add your own list of buttons. For example, I need some way of 'deleting' files and it would be really nice to have the delete button there. In the minimal form, the delete button could be one of the default ones.

**Comment by Ks89** [comment]
Yes, this is another interesting feature.
Probably, the best solution is to use an array of css classes defined globally in your app, so also angular-modal-gallery could use their.

For instance something like ['my-custom-delete','fa-exturl','fa-download','my-custom-close'].
Where my-custom-delete and my-custom-close are custom css classes defined somewhere by user. To achieve this, I really need to rewrite the entire css using flexbox, because I need a better way to align icons and so on.

Also, I should try to remove font-awesome as a dependency and write custom svg default icons.

Mmm... 4.0.0 is becoming too big. I have to think about it. Probably, I should schedule only some features for 4.0.0 (to release it quickly at about the beginning of 2018) and release another major version in late 2018 with all other missing features.

related to #80

**Comment by Ks89** [comment]
Same issue here #79

**Comment by Ks89** [comment]
Completed. I'll release this feature in 5.0.0.
At the moment, I'm working on a private branch locally.
Please be patient, I'll release the first beta/alpha in one month or less.

If you want to be a beta tester, feel free to answer me here.

**Comment by Enngage** [comment]
Awesome! I will definitely update once this is out and see how that works. On another note - have you tested your release with Angular 5? I suppose that if you are planning on maintaining this library it would be nice to have the major versions aligned with Angular.

**Comment by Ks89** [comment]
Yes. I published angular-modal-gallery 4.x.x with the official support for Angular 5 and angular package format v4.
So, the next major with the feature requested here will be 5.x.x

**Comment by matiishyn** [comment]
This is how we add custom btn:
```ts
angularModalGalleryButtonsConfig: ButtonsConfig = {
    visible: true,
    strategy: ButtonsStrategy.CUSTOM,
    buttons: [
      {
        className: 'fa fa-star-o white',
        type: ButtonType.CUSTOM,
        ariaLabel: 'custom favorite aria label',
        title: 'Favorite',
        fontSize: '30px'
      },
```
But how do you handle click on it?

**Comment by Ks89** [comment]
You are right, I forgot to add this thing to both examples and doc website.

I'll update this weekend. 

You should use onBefore Hook and after hook, because a click on custom buttons executes these two methods one after the other without to do anything in the middle.
