### ISSUE TITLE
Modal-gallery In a Modal

### ISSUE THREAD

**Issue by daylenlim** [Ks89/angular-modal-gallery#95]
Is it possible to use Modal-gallery in a Modal?

I'm using the BsModalService to generate the modal.
https://valor-software.com/ngx-bootstrap/#/modals

my result as below ->

![capture](https://user-images.githubusercontent.com/7201732/31395916-86209338-ae14-11e7-9fb6-2aa727ba5f39.JPG)

my expected result is the gallery can cover the full screen,
any suggestions?

**Comment by Ks89** [comment]
This is a good question. I never thought about this scenario.

I'll schedule this for version 4.0.0 or greater.

**Comment by daylenlim** [comment]
Thanks for your prompt reply. 👍 
I'm looking forward to version 4.0.0.  :)

**Comment by Ks89** [comment]
@daylenlim Hi, can I ask you a small thing?

Do you have a working example of a Modal dialog on https://plnkr.co/ with the latest beta version of ngx-bootstrap 2?

I started to work on this feature, but I need small help, because it is quite difficult.

**Comment by Ks89** [comment]
It could be a good idea to test both ngx-bootstrap 2 and ng-bootstrap (latest releases, also if still beta versions)

If someone want to help me, please provide me two plunkr's examples with these libraries to show modal dialogs. Also, If you want to add angular-modal-gallery inside the dialogs to these examples, it will be really appreciated.

This feature might be quite difficult to implement, so I need help. Otherwise, it will be probably released in future minor versions of angular-modal-gallery 5.x.x and not with 5.0.0.

I'll add every testers and contributors to the official readme of 5.0.0, when released.

**Comment by SeanBreathnach** [comment]
I had this issue (an image gallery running from within a modal)
Adding the below to my styles fixed it for me:

`.modal.show .modal-dialog { transform:none; }`

**Comment by Ks89** [comment]
Interesting  @SeanBreathnach  I'll try it.

> Adding the below to my styles

Did you add that css to angular's global style? Or inside the component with the modal gallery?

**Comment by Ks89** [comment]
Interesting I'll try this weekend

**Comment by Ks89** [comment]
Hi @SeanBreathnach which library are you using to create modal dialog?

**Comment by Ks89** [comment]
Fully implemented (branch `800`) thanks to angular/cdk and scheduled for 8.0.0-beta.1 that is coming soon.

I close this issue because already done and It will be available in a beta release in some days.
